/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected/users/index'
import { Route as ProtectedSubscriptionsIndexRouteImport } from './routes/_protected/subscriptions/index'
import { Route as ProtectedPackagesIndexRouteImport } from './routes/_protected/packages/index'
import { Route as ProtectedOrdersIndexRouteImport } from './routes/_protected/orders/index'
import { Route as ProtectedSubscriptionsCreateRouteImport } from './routes/_protected/subscriptions/create'
import { Route as ProtectedPackagesCreateRouteImport } from './routes/_protected/packages/create'
import { Route as ProtectedPackagesPlanIdUpdateRouteImport } from './routes/_protected/packages/$planId/update'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSubscriptionsIndexRoute =
  ProtectedSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPackagesIndexRoute = ProtectedPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOrdersIndexRoute = ProtectedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSubscriptionsCreateRoute =
  ProtectedSubscriptionsCreateRouteImport.update({
    id: '/subscriptions/create',
    path: '/subscriptions/create',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPackagesCreateRoute = ProtectedPackagesCreateRouteImport.update({
  id: '/packages/create',
  path: '/packages/create',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPackagesPlanIdUpdateRoute =
  ProtectedPackagesPlanIdUpdateRouteImport.update({
    id: '/packages/$planId/update',
    path: '/packages/$planId/update',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/packages/create': typeof ProtectedPackagesCreateRoute
  '/subscriptions/create': typeof ProtectedSubscriptionsCreateRoute
  '/orders/': typeof ProtectedOrdersIndexRoute
  '/packages/': typeof ProtectedPackagesIndexRoute
  '/subscriptions/': typeof ProtectedSubscriptionsIndexRoute
  '/users/': typeof ProtectedUsersIndexRoute
  '/packages/$planId/update': typeof ProtectedPackagesPlanIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/packages/create': typeof ProtectedPackagesCreateRoute
  '/subscriptions/create': typeof ProtectedSubscriptionsCreateRoute
  '/orders': typeof ProtectedOrdersIndexRoute
  '/packages': typeof ProtectedPackagesIndexRoute
  '/subscriptions': typeof ProtectedSubscriptionsIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
  '/packages/$planId/update': typeof ProtectedPackagesPlanIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/packages/create': typeof ProtectedPackagesCreateRoute
  '/_protected/subscriptions/create': typeof ProtectedSubscriptionsCreateRoute
  '/_protected/orders/': typeof ProtectedOrdersIndexRoute
  '/_protected/packages/': typeof ProtectedPackagesIndexRoute
  '/_protected/subscriptions/': typeof ProtectedSubscriptionsIndexRoute
  '/_protected/users/': typeof ProtectedUsersIndexRoute
  '/_protected/packages/$planId/update': typeof ProtectedPackagesPlanIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/packages/create'
    | '/subscriptions/create'
    | '/orders/'
    | '/packages/'
    | '/subscriptions/'
    | '/users/'
    | '/packages/$planId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/packages/create'
    | '/subscriptions/create'
    | '/orders'
    | '/packages'
    | '/subscriptions'
    | '/users'
    | '/packages/$planId/update'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/dashboard'
    | '/_protected/packages/create'
    | '/_protected/subscriptions/create'
    | '/_protected/orders/'
    | '/_protected/packages/'
    | '/_protected/subscriptions/'
    | '/_protected/users/'
    | '/_protected/packages/$planId/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/subscriptions/': {
      id: '/_protected/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof ProtectedSubscriptionsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/packages/': {
      id: '/_protected/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof ProtectedPackagesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/orders/': {
      id: '/_protected/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof ProtectedOrdersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/subscriptions/create': {
      id: '/_protected/subscriptions/create'
      path: '/subscriptions/create'
      fullPath: '/subscriptions/create'
      preLoaderRoute: typeof ProtectedSubscriptionsCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/packages/create': {
      id: '/_protected/packages/create'
      path: '/packages/create'
      fullPath: '/packages/create'
      preLoaderRoute: typeof ProtectedPackagesCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/packages/$planId/update': {
      id: '/_protected/packages/$planId/update'
      path: '/packages/$planId/update'
      fullPath: '/packages/$planId/update'
      preLoaderRoute: typeof ProtectedPackagesPlanIdUpdateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedPackagesCreateRoute: typeof ProtectedPackagesCreateRoute
  ProtectedSubscriptionsCreateRoute: typeof ProtectedSubscriptionsCreateRoute
  ProtectedOrdersIndexRoute: typeof ProtectedOrdersIndexRoute
  ProtectedPackagesIndexRoute: typeof ProtectedPackagesIndexRoute
  ProtectedSubscriptionsIndexRoute: typeof ProtectedSubscriptionsIndexRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
  ProtectedPackagesPlanIdUpdateRoute: typeof ProtectedPackagesPlanIdUpdateRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedPackagesCreateRoute: ProtectedPackagesCreateRoute,
  ProtectedSubscriptionsCreateRoute: ProtectedSubscriptionsCreateRoute,
  ProtectedOrdersIndexRoute: ProtectedOrdersIndexRoute,
  ProtectedPackagesIndexRoute: ProtectedPackagesIndexRoute,
  ProtectedSubscriptionsIndexRoute: ProtectedSubscriptionsIndexRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
  ProtectedPackagesPlanIdUpdateRoute: ProtectedPackagesPlanIdUpdateRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
