/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedPackagesIndexRouteImport } from './routes/_protected/packages/index'
import { Route as ProtectedOrdersIndexRouteImport } from './routes/_protected/orders/index'
import { Route as ProtectedPackagesCreateRouteImport } from './routes/_protected/packages/create'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPackagesIndexRoute = ProtectedPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOrdersIndexRoute = ProtectedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPackagesCreateRoute = ProtectedPackagesCreateRouteImport.update({
  id: '/packages/create',
  path: '/packages/create',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/packages/create': typeof ProtectedPackagesCreateRoute
  '/orders/': typeof ProtectedOrdersIndexRoute
  '/packages/': typeof ProtectedPackagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/packages/create': typeof ProtectedPackagesCreateRoute
  '/orders': typeof ProtectedOrdersIndexRoute
  '/packages': typeof ProtectedPackagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/packages/create': typeof ProtectedPackagesCreateRoute
  '/_protected/orders/': typeof ProtectedOrdersIndexRoute
  '/_protected/packages/': typeof ProtectedPackagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/packages/create' | '/orders/' | '/packages/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/packages/create' | '/orders' | '/packages'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/dashboard'
    | '/_protected/packages/create'
    | '/_protected/orders/'
    | '/_protected/packages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/packages/': {
      id: '/_protected/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof ProtectedPackagesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/orders/': {
      id: '/_protected/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof ProtectedOrdersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/packages/create': {
      id: '/_protected/packages/create'
      path: '/packages/create'
      fullPath: '/packages/create'
      preLoaderRoute: typeof ProtectedPackagesCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedPackagesCreateRoute: typeof ProtectedPackagesCreateRoute
  ProtectedOrdersIndexRoute: typeof ProtectedOrdersIndexRoute
  ProtectedPackagesIndexRoute: typeof ProtectedPackagesIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedPackagesCreateRoute: ProtectedPackagesCreateRoute,
  ProtectedOrdersIndexRoute: ProtectedOrdersIndexRoute,
  ProtectedPackagesIndexRoute: ProtectedPackagesIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
